# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Plotsquared Docs
site_url: https://themeinerlp.github.io/plotsquared_test_docs/
repo_url: https://github.com/TheMeinerLP/plotsquared_test_docs
repo_name: TheMeinerLP/plotsquared_test_docs

theme:
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  name: material
  locale: en
  features:
  - navigation.sections
  - content.code.copy
  - content.code.select
  - search.suggest
  - search.highlight
  - search.share
  font:
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang:
        - en
